version: 2
jobs:
  frontend_build:
    working_directory: ~/repo
    docker:
      - image: node:10.16.3
    steps:
      - checkout
      - run:
          name: Install dependency
          command: yarn
          working_directory: frontend
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
          working_directory: frontend
      - run:
          name: Install firebase-tools
          command: npm install --dev firebase-tools
          working_directory: frontend
      - run:
          name: Build
          command: npm run build
          working_directory: frontend


