version: 2
jobs:
  build:
    working_directory: ~/kingkong_playlist/backend
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout:
          path: ~/kingkong_playlist
      - run:
          command: |
            gem update --system
            gem install bundler
      - run:
          name: プロジェクトローカルにGemをインストールする設定
          command: bundle config set --local path 'vendor/bundle'
      - run:
          command: bundle check || bundle install
      - save_cache:
          key: kingkong_playlist-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          command: bin/rails db:create db:migrate db:schema:load --trace
      - run:
          command: bundle exec rspec
      - store_test_results:
          path: /tmp/test-results      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build