version: 2
jobs:
  build:
    working_directory: ~/kingkong_playlist/backend
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout:
          path: ~/kingkong_playlist
      - restore_cache:
          keys:
            - kingkong_playlist-{{ checksum "Gemfile.lock" }}
            - kingkong_playlist-
      - run:
          command: |
            gem update --system
            gem install bundler
      - run:
          name: プロジェクトローカルにGemをインストールする設定
          command: bundle config set --local path 'vendor/bundle'
      - run:
          command: bundle check || bundle install
      - save_cache:
          key: kingkong_playlist-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          command: bin/rails db:create db:migrate db:schema:load --trace
      - run:
          command: bundle exec rspec
      - store_test_results:
          path: /tmp/test-results
  frontend-deploy:
    working_directory: ~/kingkong_playlist/frontend
    docker:
      - image: node:10.16.3
    steps:
      - checkout:
          path: ~/kingkong_playlist
      - restore_cache:
          keys: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          command: yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          command: yarn add --dev firebase-tools
      - run:
          command: yarn run build
      - run:
          command: node_modules/.bin/firebase deploy --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_DEPLOY_TOKEN"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - frontend-deploy:
          requires:
            - build
          filters:
            branches:
              only: master